server:
  port: ":8080"
  mode: "debug"

converter:
  # 根据实际情况修改，例如 "/usr/bin/soffice"
  libreoffice_path: "soffice"
  output_dir: "./converted"
  upload_dir: "./uploads"
log:
  # slog 相关配置
  level: "info" # debug, info, warn, error
  format: "text" # text 或 json

  # lumberjack 相关配置
  filename: "logs/app.log" # 日志文件路径
  max_size: 100       # 每个日志文件的最大尺寸 (MB)
  max_backups: 5      # 保留的旧日志文件数量
  max_age: 30         # 保留旧日志文件的最大天数
  compress: false     # 是否压缩旧日志文件